# This is a basic workflow to help you get started with Actions
name: CI-CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains multiple jobs
  build_test:
    # The type of runner that the job will run on
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # install applicaion dependencies
      - name: Install dependencies
        run: |
          npm install

      - name: "Create env file"
        run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Stop and Remove existing container
        run: |
          docker stop SolarBackend || true
          docker rm SolarBackend || true

      - name: Build Docker image
        run: docker build -t aerscs/solar-backend-docker:latest .

      - name: Run Docker container
        run: docker run -d --restart unless-stopped -p 3000:3000 --name SolarBackend aerscs/solar-backend-docker:latest
